name: CIVisibility

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      datadog-agent:
        image: gcr.io/datadoghq/agent:latest
        ports:
        - 8126:8126
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_INSIDE_CI: "true"
          DD_HOSTNAME: "none"

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Install Datadog Trace
      run: |
        dotnet tool install -g dd-trace
        echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH
        
#    - name: Restore dependencies
#      run: dotnet restore
      
#    - name: Build
#      run: dotnet build --no-restore
      
#    - name: Test
#      run: dotnet test --no-build --verbosity normal

    - name: Test
      run: dd-trace --dd-service=TestService --dd-env=ci -- dotnet test --no-restore
      env:
        AWS_REGION: "eu-west-1"
        DD_AGENT_HOST: datadog-agent
        DD_TRACE_AGENT_PORT: 8126
        DD_TRACE_DEBUG: true
